### ISSUE TITLE
[UE] Performance?

### ISSUE THREAD

**Issue by faseceroo** [Tencent/puerts#1226]
Hi, I recently discovered puerts and I'm absolutely delighted about how easy it is to program in UE with this invaluable tool, once past the ups and downs of the installation that took me a while to understand.

I wonder if anyone did some performance measurements, how well does it compare to using visual blueprints, is it faster? How well does it compare in speed with respect to Unlua?

If someone has made some benchmmants it would be very interesting to know them. Thanks and sorry for the question it may be a little off-topic.

**Comment by chexiongsheng** [comment]
The performance of such scripting solutions consists of two parts: 
* script execution performance
* performance of interaction between scripts and native code. 

For puerts  V8 backend version (or Node.js version), scripts are executed within the Google V8 virtual machine. A comparison between this virtual machine and the Lua virtual machine is easily available online. Unlua uses the official version of Lua, which is far less performant than V8 with JIT support. When comparing with blueprints, V8 likely has a performance advantage due to its JIT support. As for the interaction between scripts and native code, there is some test case for puerts: 
typescript: https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/TsProj/PerfTest.ts
c++: https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Source/puerts_unreal_demo/TGUnitTestCallee.h
test result: https://github.com/Tencent/puerts/discussions/858

Which you can write the same test case in blueprints and Unlua, compare with puerts in the same machine.

**Comment by faseceroo** [comment]
Thank you, that is exactly what I needed to know to start working.
